### ISSUE TITLE
incorrect 2019 values

### ISSUE THREAD

**Issue by robcalon** [quintel/multi-year-charts#18]
It appears that the 2019 values are not the default dataset values and are copied from the first session id instead, for example https://myc.energytransitionmodel.com/949701,949702,949703/inputs

**Comment by marliekeverweij** [comment]
Thanks for communicating this issue. I tried to reproduce this and I did not succeed. I made a test 2050 scenario for NL on pro and started a transition path with that scenario. This is the result: [https://myc.energytransitionmodel.com/949885,949886,949887,949888/inputs](https://myc.energytransitionmodel.com/949885,949886,949887,949888/inputs)
In this transition path the 2019 values correspond with the default dataset values.

@antw could you have a look at this issue?
