### ISSUE TITLE
Region and sliders should appear

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/multi-year-charts#26]
I am testing the MYC for the deploy next week and looking into [these scenarios](https://myc-beta.energytransitionmodel.com/2171022,2171023,2171024,2171025/inputs?title=Business%20as%20Usual%202050%20-%20Marlieke).

For these scenarios (and also other scenarios):
- I do not see the region in the upperright corner
- the slider settings do not load

![Screenshot 2022-11-30 at 15 04 13](https://user-images.githubusercontent.com/32833996/204816485-08176d85-d934-4353-824d-62427edefe0b.png)

**Comment by antw** [comment]
Thanks, good catch. It was related to the new address for ETModel (beta). I've updated the MYC environment variables and redeployed the app.
