### ISSUE TITLE
Final demand queries 'fossil electricity' for transport and all sectors do not add up

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/multi-year-charts#70]
In a particular scenario path we can see the following:

![Screenshot 2024-09-12 at 09 20 17](https://github.com/user-attachments/assets/24970f13-6c68-4c34-a7f1-024d53d7af3e)

Total fossil electricity demand adds up to 124.50 PJ in 2050.

![Screenshot 2024-09-12 at 09 21 58](https://github.com/user-attachments/assets/cd192c0b-6985-4e49-bf89-bfba40b9ef0a)
While fossil electricity demand in transport adds up to 165.41 PJ. 

Will pick this up myself

**Comment by mabijkerk** [comment]
@kaskranenburgQ I delved into the issue. Both queries use different methods: one uses the EG approach and the other the G approach. In total they produce the same amount of final demand for electricity. However, they apparently handle sustainability share differently. Why this is the case, I'm sure. I think it's quicker to revise the queries to totale electricity demand and drop the difference between fossil and sustainable in the MYC.
